# Use the same base image as production for consistency
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

# Allow __pycache__ and copy files instead of hardlinking
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# Copy dependencies first and install everything, including dev dependencies
COPY pyproject.toml uv.lock ./  
RUN uv sync --frozen --no-install-project

#Install App
COPY . .
RUN uv sync --frozen

# Ensure the virtual environment’s binaries are in the PATH so that commands like `uvicorn` are found.
ENV PATH="/app/.venv/bin:$PATH"

# Clear any inherited entrypoint to avoid unexpected behavior.
ENTRYPOINT []


CMD ["pytest"]
